name = "mcu-sync"
main = "worker.js"
compatibility_date = "2026-09-01"

# デプロイ前に `npx wrangler kv namespace create SYNC` を実行し、
# 出力された id で下の 84004cedc76a42caa45b9618993635fb を置き換える
[[kv_namespaces]]
binding = "SYNC"
id = "84004cedc76a42caa45b9618993635fb"
